import { Geist, Geist_Mono, Playwrite_AR_Guides, Poppins, Roboto } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar/Navbar";
// import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/provider/NextAuthProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//my website font
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

//custom theme 

const poppips = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"]
})
export const metadata = {
  title: "Bike",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <NextAuthProvider>
    <html lang="en">
      <body className={`${poppips.className} $ antialiased`}>
        
          {/* <Navbar /> */}

          <div className="min-h-[calc(100vh-472px)] bg-[#ffffff]">
              
       
              <div>
                <main>{children}</main>
              </div>
            
            <ToastContainer position="top-right" />
          </div>

          {/* <Footer /> */}
          

      </body>
    </html>
         </NextAuthProvider>   
  );
}
